/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as LanguageselectionRouteImport } from './routes/languageselection'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticededicatedExerciseIdRouteImport } from './routes/practicededicated.$exerciseId'
import { Route as LessonLessonIdRouteImport } from './routes/lesson.$lessonId'

const SignupLazyRouteImport = createFileRoute('/signup')()
const LoginLazyRouteImport = createFileRoute('/login')()

const SignupLazyRoute = SignupLazyRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageselectionRoute = LanguageselectionRouteImport.update({
  id: '/languageselection',
  path: '/languageselection',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticededicatedExerciseIdRoute =
  PracticededicatedExerciseIdRouteImport.update({
    id: '/practicededicated/$exerciseId',
    path: '/practicededicated/$exerciseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LessonLessonIdRoute = LessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/languageselection': typeof LanguageselectionRoute
  '/practice': typeof PracticeRoute
  '/login': typeof LoginLazyRoute
  '/signup': typeof SignupLazyRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/practicededicated/$exerciseId': typeof PracticededicatedExerciseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/languageselection': typeof LanguageselectionRoute
  '/practice': typeof PracticeRoute
  '/login': typeof LoginLazyRoute
  '/signup': typeof SignupLazyRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/practicededicated/$exerciseId': typeof PracticededicatedExerciseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/languageselection': typeof LanguageselectionRoute
  '/practice': typeof PracticeRoute
  '/login': typeof LoginLazyRoute
  '/signup': typeof SignupLazyRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/practicededicated/$exerciseId': typeof PracticededicatedExerciseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/languageselection'
    | '/practice'
    | '/login'
    | '/signup'
    | '/lesson/$lessonId'
    | '/practicededicated/$exerciseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/languageselection'
    | '/practice'
    | '/login'
    | '/signup'
    | '/lesson/$lessonId'
    | '/practicededicated/$exerciseId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/languageselection'
    | '/practice'
    | '/login'
    | '/signup'
    | '/lesson/$lessonId'
    | '/practicededicated/$exerciseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LanguageselectionRoute: typeof LanguageselectionRoute
  PracticeRoute: typeof PracticeRoute
  LoginLazyRoute: typeof LoginLazyRoute
  SignupLazyRoute: typeof SignupLazyRoute
  LessonLessonIdRoute: typeof LessonLessonIdRoute
  PracticededicatedExerciseIdRoute: typeof PracticededicatedExerciseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/languageselection': {
      id: '/languageselection'
      path: '/languageselection'
      fullPath: '/languageselection'
      preLoaderRoute: typeof LanguageselectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practicededicated/$exerciseId': {
      id: '/practicededicated/$exerciseId'
      path: '/practicededicated/$exerciseId'
      fullPath: '/practicededicated/$exerciseId'
      preLoaderRoute: typeof PracticededicatedExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$lessonId': {
      id: '/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LanguageselectionRoute: LanguageselectionRoute,
  PracticeRoute: PracticeRoute,
  LoginLazyRoute: LoginLazyRoute,
  SignupLazyRoute: SignupLazyRoute,
  LessonLessonIdRoute: LessonLessonIdRoute,
  PracticededicatedExerciseIdRoute: PracticededicatedExerciseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
